$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "https://mindscript.dev/schemas/bdd/openspec.core-1.0.json"
title: "MindScript Core BDD"
type: object
required: [profile, kind, meta, scenarios]
additionalProperties: false

properties:
  profile:
    type: string
    const: "https://mindscript.dev/profiles/bdd/openspec.core"

  kind:
    type: string
    const: "bdd-core"

  meta:
    type: object
    required: [id, title]
    additionalProperties: false
    properties:
      id:
        type: string
        description: "Identifier for this scenario collection (e.g., AUTH-101.core)"
        pattern: "^[A-Z]+-[0-9]+(\\.[A-Za-z0-9_-]+)*$"
      title:
        type: string
        minLength: 3
      tags:
        type: array
        uniqueItems: true
        items: { type: string }

  background:
    type: object
    additionalProperties: false
    properties:
      steps:
        type: array
        items: { $ref: "#/$defs/step" }

  scenarios:
    type: array
    minItems: 1
    items: { $ref: "#/$defs/scenario" }

$defs:
  step:
    type: object
    additionalProperties: false
    required: [keyword, text]
    properties:
      keyword:
        type: string
        enum: ["Given", "When", "Then", "And", "But"]
      text:
        type: string
        minLength: 1
      table:
        description: "Optional data table. Each inner array is a row."
        type: array
        items:
          type: array
          items: { type: string }
      doc:
        description: "Optional docstring-style block"
        type: string

  scenario:
    type: object
    additionalProperties: false
    required: [id, name, steps]
    properties:
      id:
        type: string
        description: "Lowercase slug identifier"
        pattern: "^[a-z0-9-]+$"
      name:
        type: string
        minLength: 3
      tags:
        type: array
        uniqueItems: true
        items: { type: string }
      outline:
        type: boolean
        description: "If true, 'examples' parameterize step text"
      examples:
        description: "Optional parameter sets for outlines"
        type: array
        items:
          type: object
          additionalProperties: { type: string }
      steps:
        type: array
        minItems: 1
        items: { $ref: "#/$defs/step" }
