$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "https://mindscript.dev/schemas/@software-1.0.json"
title: "MindScript Profile: @software"
type: object
required: [profile, kind, meta, requirements]
properties:
  profile:
    type: string
    format: uri
    const: "https://mindscript.dev/profiles/@software"

  imports:
    type: array
    description: "Optional list of subprofile URLs (dot-namespaced) to import"
    uniqueItems: true
    items:
      type: string
      format: uri

  kind:
    type: string
    const: "software"

  meta:
    type: object
    required: [id, title, owner, priority]
    properties:
      id:
        type: string
        pattern: "^[A-Z]+-[0-9]+$"
      title:
        type: string
        minLength: 3
      owner:
        type: string
      priority:
        type: string
        enum: ["P0","P1","P2","P3"]
      labels:
        type: array
        uniqueItems: true
        items: { type: string }

      # Optional default BDD binding for the entire spec
      bdd:
        type: object
        additionalProperties: false
        properties:
          source:
            type: string
            format: uri
            description: "URL of an external BDD profile (see bdd-registry.yaml)"
          feature_path:
            type: string
            description: "Path/URL to an external BDD file"
          scenario:
            type: string
            description: "Scenario name or identifier"

  requirements:
    type: array
    minItems: 1
    items:
      type: object
      required: [id, statement, criteria]
      properties:
        id:
          type: string
          pattern: "^[A-Z]+-[0-9]+(\\.[0-9]+)*$"
        statement:
          type: string
          minLength: 5
        rationale:
          type: string
        criteria:
          type: array
          minItems: 1
          items:
            type: object
            required: [id, text, type]
            properties:
              id:
                type: string
                pattern: "^[A-Z]+-[0-9]+(\\.[0-9]+)*$"
              text:
                type: string
                minLength: 5
              type:
                type: string
                enum: ["functional","nonfunctional","security","accessibility"]

              # External BDD binding only
              bdd_ref:
                type: object
                required: [source]
                additionalProperties: false
                properties:
                  source:
                    type: string
                    format: uri
                    description: "URL of a BDD profile (e.g. https://mindscript.dev/profiles/bdd/behave)"
                  path:
                    type: string
                    description: "Path/URL to external BDD file"
                  scenario:
                    type: string
                    description: "Scenario name to bind"
